server {
	listen 80;
	listen [::]:80;

	listen 443      ssl;
	listen [::]:443 ssl;

	ssl_certificate /etc/letsencrypt/live/theclashfruit.me/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/theclashfruit.me/privkey.pem;

	server_name www.theclashfruit.me theclashfruit.me;

	root /var/www/theclashfruit.me;
	index index.php index.php;

	add_header Access-Control-Allow-Origin "*";
	add_header Strict-Transport-Security   "max-age=5184000; includeSubDomains";

	error_page 500 /500.html;
	error_page 404 /404.html;
	error_page 403 /403.html;

	location / {
		try_files $uri $uri.html $uri/ @extensionless-php;
	}

	location ~ \.php$ {
		include snippets/fastcgi-php.conf;
		fastcgi_pass unix:/run/php/php7.4-fpm.sock;
	}

	location ~ ^/post/(.+)/?$ {
		try_files $uri /post.php?id=$1;
	}

	location ~ /\.ht {
		deny all;
	}

	location ~ /sitemap\.xml$ {
		try_files $uri /sitemap.php;
	}

	location ~ /blog_sitemap\.xml$ {
		try_files $uri /blog_sitemap.php;
	}

	location /config {
		deny all;
		return 404;
	}

	location ~ /\.env$ {
		deny all;
		return 404;
	}

	location @extensionless-php {
		rewrite ^(.*)$ $1.php last;
	}
}
